
- name: Debug host target
  hosts: switches
  gather_facts: false
  tasks:
    - name: Show connection variables
      community.ciscosmb.command:
        commands:
          - show system
      register: iface_out
