---
- name: Export Cisco SMB interface descriptions to CSV
  hosts: sw-gpd-s2
  gather_facts: no

  tasks:
    - name: Run "show system"
      community.ciscosmb.command:
        commands:
          - show system
      register: run_cfg

