---
- name: Skonfiguruj vlany, mode, shutdown na portach oprócz tych z tagiem pomijanego
  community.ciscosmb.command:
    commands: "{{ port_commands }}"
  vars:
    port_commands: >-
      {{
        ['conf t', 'int ' ~ item.key]
        +
        (
          ['switchport mode access']
          if item.value.mode == 'access'
          else
          ['switchport mode trunk']
          if item.value.mode == 'tagged'
          else
          []
        )
        +
        (
          (
            ['switchport access vlan ' ~ (item.value.access_vlan | string)]
            if item.value.access_vlan | string | trim | length > 0
            else
            ['no switchport access vlan']
          )
          if item.value.mode == 'access'
          else
          []
        )
        +
        (
          (
            ['switchport trunk native vlan ' ~ (item.value.access_vlan | string)]
            if item.value.access_vlan | string | trim | length > 0
            else
            ['no switchport trunk native vlan']
          )
          if item.value.mode == 'tagged'
          else
          []
        )
        +
        (
          (
            ['switchport trunk allowed vlan ' ~ item.value.trunk_vlans]
            if item.value.trunk_vlans | string | trim | length > 0
            else
            ['no switchport trunk allowed vlan']
          )
          if item.value.mode == 'tagged'
          else
          []
        )
        +
        (
          ['no shutdown']
          if item.value.enabled | default(true) | bool
          else
          ['shutdown']
        )
        +
        ['end']
      }}
  loop: "{{ nb_iface_cfg_map | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - not ansible_check_mode
    - ciscosmb_port_sync_skip_tag not in (item.value.tags | default([]))