- name: Zbuduj mapę konfiguracji portów z NetBox
  ansible.builtin.import_tasks: build_port_cfg_map.yml

- name: Pobierz aktualny stan portów ze switcha
  ansible.builtin.import_tasks: read_current_port_cfg.yml

- name: Zbuduj listę portów wymagających zmian
  ansible.builtin.import_tasks: build_changed_ports.yml

- name: Debug informacji o portach
  ansible.builtin.import_tasks: debug.yml

- name: Skonfiguruj tylko porty z różnicami
  ansible.builtin.import_tasks: configure_ports.yml