- name: Konfiguracja vlan na access portach
  hosts: switches
  gather_facts: no

  tasks:
    - name: Ustawienie VLANu
      community.ciscosmb.command:
        commands:
          - conf t
          - 'int {{ item }}'
          - switchport access vlan 1000
          - end
          - write memory
      loop: '{{ access_interfaces }}'
      register: vlan_output
