- name: Usuń SNMP
  community.ciscosmb.command:
    commands:
      - conf t
      - "no snmp-server community netbox 192.168.2.70"
      - "snmp-server group m24 v3 auth read DefaultSuper"
      - "snmp-server user netbox m24 v3 auth sha 6wJ5U2+?PX&uJsn+_2"
      - end
      
- name: Zapisz konfigurację (raz)
  community.ciscosmb.command:
    commands:
      - write memory

