all:
  children:

    switches_mroczen:
      hosts:
        sw-lpd-01: {}
        sw-lpd-02: {}
        sw-lpd-03: {}
        sw-lpd-04: {}
        sw-lpd-05: {}
        sw-lpd-06: {}
        sw-lpd-07: {}
        sw-lpd-08: {}
        sw-lpd-09: {}
        sw-lpd-10: {}
        sw-lpd-11: {}
        sw-lpd-p: {}
        sw-gpd-sa: {}
        sw-lpd-z-sa: {}
        sw-gpd-s1: {}
        sw-lpd-1b-1: {}
        sw-lpd-1b-2: {}
        sw-lpd-1b-3: {}
        sw-gpd-s2: {}
        sw-lpd-2b-3: {}
        sw-lpd-2b-1: {}
        sw-lpd-2b-2: {}
        sw-gpd-ser-sw: {}
        sw-gpd-ser-eth: {}
        sw-gpd-s3: {}
        sw-lpd-3b: {}
        sw-lpd-z-s1: {}
        sw-lpd-m: {}

    switches_leka:
      hosts:
        sw-prod-01: {}
        sw-prod-02: {}
        sw-prod-03: {}
        sw-prod-04: {}
        sw-prod-05: {}
        sw-prod-06: {}
        sw-prod-07: {}
        # sw-prod-08: {} do sprawdzenia unable to connect SSH
        sw-prod-09: {}
        sw-prod-10: {}
        sw-prod-11: {}
        sw-prod-12: {}
        sw-prod-13: {}
        sw-rodz-01: {}
        sw-rodz-02: {}
        # sw-szef: {} nie cisco
        sw-prez-01: {}
        sw-prez-02: {}

    switches_mirtex:
      hosts:
        sw-hurt-01: {}
        sw-hurt-02: {}
        sw-hurt-03: {}

    switches_mianowice:
      hosts:
        sw-mian-01: {}
        sw-mian-02: {}

    switches:
      children:
        switches_mroczen: {}
        switches_leka: {}
        switches_mirtex: {}
        switches_mianowice: {}

    routers:
      hosts:
        rt-mroczen: {}
        rt-mroczen-kamery: {}
        rt-leka: {}
        rt-leka-kamery: {}
        rt-mirtex: {}
        rt-mirtex-kamery: {}
        rt-mianowice: {}

    ucks:
      hosts:
        uck-mroczen: {}
        


    domain_servers:
      hosts:
        weblogic-dbo: {}
        m24iis: {}
        shadow: {}
        m24ter: {}
        suse: {}
        todys: {}
        weblogic-app: {}
        oxa: {}
        burn: {}
        clover: {}
        bms: {}
        iris: {}
        t-magazyn: {}
        irini2: {}
        eos: {}
        m24srv: {}
        eris: {}
        sub-ca: {}
        enyo: {}
        nevo: {}
        blaze: {}
        render: {}

    not_domain_servers:
      hosts:
        pulsar0905: {}
        pulsar2: {}
        mirjants: {}
        kadry_xp: {}
        irini: {}
        ca: {}
        netbox: {}
        pulsar: {}
        zabbix: {}
        thorn: {}
        ares: {}
        evo: {}
        onyx: {}
        ivo: {}
        axio: {}
        nexo: {}

    servers:
      children:
        domain_servers: {}
        not_domain_servers: {}
