ansible_host: 10.10.250.16
ansible_password: "{{ sw_gpd_s1_pass }}"

d_ports:
  - gi1/0/7
  - gi1/0/38
  
ap_ports:
  - gi1/0/1
  - gi1/0/3
  - gi1/0/4
  - gi1/0/5
  - gi1/0/13
  - gi1/0/15
