ansible_host: 10.10.250.22
ansible_password: "{{ sw_lpd_3b_pass }}"

kd_ports:
  - gi1/0/46
  - gi1/0/47
  - gi1/0/48

voip_ports:
  - gi1/0/20
  - gi1/0/26

d_ports:
  - gi1/0/7
  - gi1/0/13
  - gi1/0/14
  - gi1/0/28
  - gi1/0/30
  - gi1/0/43

ap_ports:
  - gi1/0/1
  - gi1/0/2
  - gi1/0/3
  - gi1/0/4
