ansible_host: 10.10.250.28
ansible_password: "{{ sw_lpd_m_pass }}"
ansible_network_cli_ssh_type: paramiko
ansible_paramiko_host_key_checking: false
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o HostKeyAlgorithms=+ssh-rsa
  -o PubkeyAcceptedAlgorithms=+ssh-rsa
  
kd_ports:
  - gi1/0/23
  - gi1/0/24
  
ap_ports:
  - gi1/0/5
  - gi1/0/7
  - gi1/0/8
