---
- name: Pobranie startup-config z Cisco SMB
  hosts: switches
  gather_facts: no
  
  vars:
    backup_root: "/var/lib/tftpboot/backups"

  pre_tasks:
    - name: Wyznacz identyfikator backupu (raz, na localhost)
      run_once: true
      set_fact:
        backup_run_id: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

  tasks:
    - name: Utworz katalog na backupy dla tej daty
      delegate_to: localhost
      run_once: true
      become: true
      file:
        path: "{{ backup_root }}/{{ hostvars[ansible_play_batch[0]].backup_run_id }}"
        state: directory
        owner: tftp
        group: tftp
        mode: '0775'
        
    - name: Uruchom "show startup-config"
      ansible.netcommon.cli_command:
        command: show startup-config
      register: startup_cfg

    - name: Zapisz startup-config do lokalnego pliku
      delegate_to: localhost
      become: true
      copy:
        content: "{{startup_cfg.stdout}}"
        dest: "{{ backup_root }}/{{ hostvars[ansible_play_batch[0]].backup_run_id }}/{{ inventory_hostname }}-startup-config.txt"
        owner: tftp
        group: tftp
        mode: '0644'
      
